### ISSUE TITLE
License headers inconsistent with LICENSE.txt

### ISSUE THREAD

**Issue by sebastic** [ossimlabs/ossim#113]
In DaytonaBeach-2.0.0 the headers were relicensed from MIT to LGPL according to changes like this:
```diff
@@ -1,14 +1,14 @@
 //*******************************************************************
 // Copyright (C) 2000 ImageLinks Inc.
 //
-// License: MIT
+// License:  LGPL
 //
 // See LICENSE.txt file in the top level directory for more details.
 //
 // Author:  Garrett Potts
 //
 //*******************************************************************
-//  $Id: ossimDoqqTileSource.h 23664 2015-12-14 14:17:27Z dburken $
+//  $Id: ossimDoqqTileSource.h 17932 2010-08-19 20:34:35Z dburken $
 #ifndef ossimDoqqTileSource_HEADER
 #define ossimDoqqTileSource_HEADER
 #include <ossim/imaging/ossimGeneralRasterTileSource.h>
@@ -56,4 +56,3 @@
 };
 
 #endif
-
```
The license header does not include the license text and instead refers to the LICENSE.txt file which includes the MIT license terms, not the LGPL.

Either the LICENSE.txt file needs to be updated to include the terms of the LGPL (version 2.1+?), or the header changes need to be reverted back to MIT.

**Comment by rkanavath** [comment]
Looking at change in Line [11](https://github.com/ossimlabs/ossim/blob/dev/include/ossim/imaging/ossimDoqqTileSource.h#L11), I guess this a mixup during merge

**Comment by sebastic** [comment]
The [Initial commit of uber-repo](https://github.com/ossimlabs/ossim/commit/f8f0bb8cadf21f115a08ed1a0eaa7c84cae3fda1) is the only commit in the blame for the random selection of files I checked. It is one of the first commits in this git repository.

It looks like the history from SVN was not preserved, there (in trunk) the files still use MIT in their header. Compare for example:

 * [svn: `include/ossim/base/ossim2dTo2dIdentityTransform.h`](https://trac.osgeo.org/ossim/browser/trunk/ossim/include/ossim/base/ossim2dTo2dIdentityTransform.h)
 * [git: `include/ossim/base/ossim2dTo2dIdentityTransform.h`](https://github.com/ossimlabs/ossim/blame/dev/include/ossim/base/ossim2dTo2dIdentityTransform.h)

```diff
@@ -1,6 +1,6 @@
 //*******************************************************************
 //
-// License: MIT
+// License:  LGPL
 // 
 // See LICENSE.txt file in the top level directory for more details.
 //
@@ -66,4 +66,3 @@
    TYPE_DATA
 };
 #endif
-
```

**Comment by rkanavath** [comment]
@gpotts, can you see if there is something left out in the svn-github synchro

**Comment by sebastic** [comment]
Is the OSSIM project planning to address this issue? It is still present in 2.1.0.

**Comment by gpotts** [comment]
I have committed a bunch of files that fixes this issue.  It will be in the next release but is checked into dev branch
