### ISSUE TITLE
Embedded copy of libjsoncpp

### ISSUE THREAD

**Issue by sebastic** [ossimlabs/ossim#115]
Please remove the libjsoncpp embedded copy and/or support using the system provided libjsoncpp library.

**Comment by rkanavath** [comment]
can we agree on removing this and adding a find_package() for libjsoncpp ?

**Comment by sebastic** [comment]
That should be sufficient, if there are no customizations to the embedded copy.

**Comment by gpotts** [comment]
I would make a modification to check the system and if not present then build the internal?  Make the internal conditional?

**Comment by rkanavath** [comment]
the internal code is using an amalgamated source. can you tell what apps depend on jsoncpp. I see util/ossimShoreLineUtil.cpp. maybe we can disable them just like hdf. the thing it adds additional dependency to projects that follow ossim.

**Comment by gpotts** [comment]
Gotcha.   I didn't put that one in.  I need to ask the person that did it and see.

**Comment by gpotts** [comment]
just sent a message out

**Comment by rkanavath** [comment]
okay. I will pick on this later when you get a response... ;)

**Comment by okramer** [comment]
I'm the culprit. Was in hurricane mode here in Florida the last couple of weeks... I'm looking into this today.

**Comment by okramer** [comment]
The embedded JSONCPP files were removed and cmake files were created/modified to search for and use external system-installed jsoncpp-devel installation.
