### ISSUE TITLE
which branch to use for pull requests?

### ISSUE THREAD

**Issue by rkanavath** [ossimlabs/ossim#116]
I am confused about which branch to use for PR in github?
on dev branch, there is still issue with geos, which as per the closed bug [1] is fixed already.
https://github.com/ossimlabs/ossim/issues/79
I am trying to push a fix for #115 , #114. I see in dev branch, there are other changes which were merged long time ago was gone.. see for instance, https://github.com/ossimlabs/ossim/pull/82

**Comment by rkanavath** [comment]
geos bug is fixed in ossimlabs/dev. Should I use the same branch for PRs now?

**Comment by cdowin** [comment]
You can do a PR into the DEV branch for any pending changes.
