### ISSUE TITLE
unable to find all the dependencies for compilation. 

### ISSUE THREAD

**Issue by ApertureSecurity** [ossimlabs/ossim#201]
Good day, So I am trying to compile this and I am running into dependency issues that I am struggling to resolve
I am running on 

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

`Linux ForeignHost 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Is there a way to install all the dependencies that are required for this? I am having difficulties finding the right lib for GEOS...

Let me know if you want any additional information..

Thanks

```
Make Warning at CMakeModules/FindGEOS.cmake:66 (message):
  Could not find GEOS
Call Stack (most recent call first):
  ../CMakeLists.txt:60 (find_package)


-- GEOS_INCLUDE_DIR=GEOS_INCLUDE_DIR-NOTFOUND
-- GEOS_LIBRARY=
CMake Error at ../CMakeLists.txt:65 (message):
  Could not find required geos package!

```

**Comment by oscarkramer** [comment]
You'll need to clone the geos repo and build it. Find it [here](https://github.com/OSGeo/geos). I am building it on my Ubuntu 16.04 LTS. Then you can either do a "sudo make install" to your system, or define an environment variable GEOS_DIR to point to your geos install directory containing lib and include. I'm linking against geos 3.6.1, but I see 3.6.2 is available, which should be OK.

**Comment by gpotts** [comment]
Hello:


I do not compile on ubuntu.   Oscar,  what do you install for libgeos?

What version of geos is it?

The find is looking in the directory geos/geom/Geometry.h  usually under /usr or /usr/local I thought.

You can override by passing -DGEOS_DIR=<root dir where geos starts>



Take care

Garrett

**Comment by gpotts** [comment]
Hello:

I am assuming you are installing the dev packages and not just the binary package of geos?  I build on CentOS and typically they are separated out with a -devel on the package name.  Not sure of the names under ubuntu.


Take care

Garrett

**Comment by oscarkramer** [comment]
I answered him via the ossimlabs ticket he opened. I downloaded geos from
the osgeo github <https://github.com/OSGeo/geos/releases>. I am building
3.6.1 but there is a 3.6.2 recently released.


<http://www.radiantsolutions.com/>

Oscar L Kramer
Senior Software Engineer
+1.863.703.4535 office <//+1.863.703.4535>
oscar.kramer@radiantsolutions.com
