### ISSUE TITLE
create source archives on github releases

### ISSUE THREAD

**Issue by rkanavath** [ossimlabs/ossim#21]
Github has an easy way to publish source archives via releases tab.

The current ossim source downloadable from download.osgeo.org contains ossim+ others.  In future releases, it would be cool to get ossim core library directly from github releases page.

Here is the blog announcement by github - https://github.com/blog/1547-release-your-software

**Comment by gpotts** [comment]
We now are creating Release tags every 3 months.  I'll close this issue.
