### ISSUE TITLE
Laguna-2.7.0 tags references same commit as Juno-2.6.2

### ISSUE THREAD

**Issue by sebastic** [ossimlabs/ossim#211]
There is currently no difference between the Laguna-2.7.0 & Juno-2.6.2 release tags, they both reference db93a35.

Please fix the tag, or delete if it was pushed prematurely.

**Comment by sebastic** [comment]
Are there any plans to fix the 2.7.0 tag even though 2.7.1 is now the most recent?

**Comment by arocnies** [comment]
Hi @sebastic, we don't plan on removing the tag as we tag versions based on the date in sync with the other OMAR apps.

Laguna-2.7.0 was incorrectly tagged as it should have been KeyWest-2.7.0. We've renamed the tag.

**Comment by sebastic** [comment]
Renaming the tag doesn't solve the issue, it still references the same commit as Juno-2.6.2.

**Comment by gpotts** [comment]
Hello:

Whether wrong or right the tag is to have a similar affect as a RedHat naming.   So it corresponds to a grouping under a distribution name.   This way we can go back to a distribution if we want to.

**Comment by sebastic** [comment]
That doesn't make much sense.

But whatever, let's just leave the 2.7.0 that's no different from 2.6.2.

I've ignore the release for the Debian package any way.
