### ISSUE TITLE
Fails to find JsonCpp on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [ossimlabs/ossim#214]
It needs this patch:
```
--- cmake/CMakeModules/FindJsonCpp.cmake.orig   2019-03-14 03:58:28 UTC
+++ cmake/CMakeModules/FindJsonCpp.cmake
@@ -16,7 +16,7 @@ set(JSONCPP_FOUND "NO")
 set(OSSIM_HAS_JSONCPP 0)

 find_path( JSONCPP_INCLUDE_DIR json/json.h
-          PATHS /usr/include/jsoncpp )
+          PATHS ${CMAKE_INSTALL_PREFIX}/include/jsoncpp )

 find_library( JSONCPP_LIBRARY NAMES "jsoncpp")

```

**Comment by BlackFrog1** [comment]
Did you install the jsoncpp library on your FreeBSD system:

- **pkg install jsoncpp**

**Comment by yurivict** [comment]
Yes, it is installed, but the directory should be ```${CMAKE_INSTALL_PREFIX}```, not ```/usr```.

**Comment by gpotts** [comment]
I am going to add it to the list.  There are other search paths.  Will check it in in a minute

**Comment by gpotts** [comment]
Checked in a modification to add the ${CMAKE_INSTALL_PREFIX}/include/jsoncpp to 0ur current search path.  Can you update and try again?

**Comment by yurivict** [comment]
6f259a9 now finds JsocCpp okay.
Could you please make a release?
