### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by ghansham** [ossimlabs/ossim#218]
We have a frame camera that covers a large area on earth by stitching frames. We found that elev classes keeps opening files and at times it crosses the system limit of 1024. Do we have a way to restrict the number of files opened by ossim Elevation classes. We are sure because we checked using lsof for the running process. We are running on rhel 7.X.

**Comment by omarossim** [comment]
Hello:

There should be an ossim preferences file referenced via an environment variable that has entries sort of like this for elevation:

elevation_manager.elevation_source1.type: dted_directory
elevation_manager.elevation_source1.connection_string: /Volumes/DataDrive/data/elevation/dted/level2
elevation_manager.elevation_source1.min_open_cells: 5
elevation_manager.elevation_source1.max_open_cells: 25
elevation_manager.elevation_source1.enabled: true
elevation_manager.elevation_source1.memory_map_cells: false


there is a min_open_cells and a max that restrict for that database.   If it’s a low res 1K cell then you can enable memory mapping and it will pull it into memory when loading.


There is a template that is annotated under

share/ossim/templates/ossim_preferences_template

Take care

Garrett

**Comment by ghansham** [comment]
Thanks. I will try the suggested solution.

**Comment by ghansham** [comment]
This worked. Actually issue was coming because ossim elevation manager threads were enabled. By default it was using 32 threads. Another observation is that same file was opened by multiple ossim elevation database instances. Is that fine?
Another suggestion was while loading the default paths for elevation, it should check existence of those paths before instantiating the relevant classes.

**Comment by omarossim** [comment]
Hello:

Yes,  just looked at the implementation.  It uses a round robin so each thread has the potential to open the same elevation data base.  The actual sources are not shared so they will get replicated.


Take care

Garrett

**Comment by omarossim** [comment]
Hello:

Looking at the check for existance and see


Take care

Garrett

**Comment by omarossim** [comment]
Hello:

For the check if exists we currenlty check to see if the database has one sell in it before adding it to the manager.  Is that what you are asking?


Take care

Garrett

**Comment by ghansham** [comment]
In the loadStandardElevationPaths method in ElevManager class, the loadElevationPath method is called for userPath and installPath without checking for their existence. It checks for existence after calling open on the path. That open is even is also not required. See line number 214 in loadElevationPath. The path existence should be checked within loadStandardElevationPaths. That may do away with with open function call which is not required if path does not exist.

**Comment by ghansham** [comment]
Regarding sharing of elevation managers, if the cells are mapped to memory, they can be shared, that can reduce the memory foot print. Am I correct?

**Comment by ghansham** [comment]
I think loadElevationPath should have existence check before calling open because this method might be getting called from multiple places other than loadStandardElevationPaths.

Regards
Ghansham

**Comment by gpotts** [comment]
Hello:

Let me see about the elevation path.   We moved checks into the factories instead because the ossimFilename is actually overloaded based on protocol type.  Some things will not work with exists checks.  The elevation database might not be file based and so a straight file exists will prematurely exit and never load a database with a different protocol for loading elevation.

Will have to think about this one for a few and see.  As it sits now,  this is typically called only during initialization of ossim.  After initialized this is no longer called.


Tale care

Garrett

**Comment by ghansham** [comment]
Ok. I agree. Yeah its only during initialization. Idea too was to speed up the startup time only.
