### ISSUE TITLE
Example usage of ossimMemoryImageSource 

### ISSUE THREAD

**Issue by ghansham** [ossimlabs/ossim#224]
Hi

I have a general raster data along with its metadata (width, height, number of bands, nullpix value and data type) as a C buffer and I want to use this data in the image chain without dumping onto the disk and going via ossimGeneralRasterTileSource route.
Seems like ossimMemoryImageSource can help in this case. Kindly guide.
Can illustrate an example of how to populate ossimMemoryImageSource from the afore-mentioned C buffer.

Ghansham and Tushar

**Comment by omarossim** [comment]
Hello:

If you want to see a quick example,  I used it in our 3-D viewer in the ossim-planet repo: ossimplanet-chip.cpp file.  Here is a cut an paste of just that part of the code:

         ossimRefPtr<ossimImageData> imageData = new ossimImageData(0,OSSIM_UINT8, 4, image->s(), image->t());
         imageData->initialize();
         
         imageData->loadTile(image->data(), ossimIrect(0,0,image->s()-1, image->t()-1), OSSIM_BIP);
         imageData->validate();
         ossimRefPtr<ossimMemoryImageSource> memSource = new ossimMemoryImageSource();
         memSource->setImage(imageData.get());
         ossimRefPtr<ossimJpegWriter> jpegWriter = new ossimJpegWriter();
         jpegWriter->connectMyInputTo(0, memSource.get());
         jpegWriter->setFilename(ossimFilename("/tmp/output.jpg"));
         jpegWriter->execute();

Take care

Garrett

**Comment by omarossim** [comment]
Hello Ghansham:

Sounds very cool!   Let me know

Take care

Garrett

**Comment by omarossim** [comment]
Hello Ghansham:


Sounds very cool!


Thank you and take care

Garrett

**Comment by ghansham** [comment]
I am not conversant with github. But can share the code making a tar ball out of it. Let me know how to share. May be by email.

**Comment by ghansham** [comment]
Hi there..

The ossimImageData class returns  all getSize*() functions ip_uint32. For files> 4GB, it limits the buffers allocation. Do we have a better class to handle it.

regards
Ghansham

**Comment by ghansham** [comment]
Right now file size I am trying is 5.7GB.

regards
Ghansham

**Comment by ghansham** [comment]
Solution could be to make the getSize*() functions return type as ossim_uint64. But I dont know how much repercussions it will have on the overall library. I mean how many changes it will call for. Or we can make a imageData specialized class for large files.

**Comment by omarossim** [comment]
Hello:

Try the dev branch now .  I made several calls all have ossim_uint64 and ossim_int64 where appropriate

Take care

Garrett

**Comment by ghansham** [comment]
Thanks a lot Sir. Can you share your email id. I wanted to share the improved code. My id is ghanshamsangar@gmail.com

**Comment by ghansham** [comment]
Just out of curosity. Will the child classes of ossimImageData be effected by 64 bit offset changes?

**Comment by ghansham** [comment]
Thanks Sir. This is working..

**Comment by omarossim** [comment]
Hello:

Good deal!   Glad it is working
