### ISSUE TITLE
Build failure on gcc 4.4.7 on rhel6

### ISSUE THREAD

**Issue by ghansham** [ossimlabs/ossim#226]
Hi...

It seems its long since I checked out the ossim branch. Atleast 3.5 years. What I am seeing is the inclusion of <atomic> in some of the header files in base directory is leading to build failure. I feel we should detect in pre build phase.

And the OpenThreads package finding is removed from CMakeLists.txt somehow. This leads to OpenThreads library and include paths not getting set during pre build phase.
Another suggestion regarding jsoncpp is to include an environment variable which could point to location where it is installed if not in standard location. Something like it is done in FindGEOS.cmake.
Regards
Ghansham

**Comment by omarossim** [comment]
Hello:

We do not use OpenThreads anymore.  We are using the C++11 standards for mutex locking ,…etc.


Take care

Garrett

**Comment by ghansham** [comment]
Thanks a lot.
