### ISSUE TITLE
up is up angle calculation grid

### ISSUE THREAD

**Issue by kjurka** [ossimlabs/ossim#279]
Only reading through the code, so I haven't actually run this, but it looks like the grid layout for the up is up angle calculation is wrong:

https://github.com/ossimlabs/ossim/blob/82417ad868fac022672335e1684bdd91d662c18c/src/imaging/ossimImageGeometry.cpp#L1538

That top row should have `-heightPercent`, right?

**Comment by gpotts** [comment]
Hello Kris:

Yes, you are correct in that assessment.   The top row should have -heightPercent so there is a bias now in the average up is up calculation.   Did you want to do a pull request?

Thank you for the catch!


Take care

Garrett
