### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by auroua** [ossimlabs/ossim#28]
I have tried many times, I can't build success, the error is:

```
[ 70%] Built target ossim
[ 71%] Built target ossim-deg2dms
[ 72%] Linking CXX executable ../../../bin/ossim-igen
[ 72%] Linking CXX executable ../../../bin/ossim-pixelflip
[ 72%] Linking CXX executable ../../../bin/ossim-senint
[ 72%] Linking CXX executable ../../../bin/ossim-viirs-proc
/usr/local/lib/libgeotiff.so: undefined reference to `TIFFSetTagExtender@LIBTIFF_4.0'
/usr/local/lib/libgeotiff.so: undefined reference to `_TIFFmemcpy@LIBTIFF_4.0'
/usr/local/lib/libgeotiff.so: undefined reference to `_TIFFrealloc@LIBTIFF_4.0'
/usr/local/lib/libgeotiff.so: undefined reference to `_TIFFmemset@LIBTIFF_4.0'
/usr/local/lib/libgeotiff.so: undefined reference to `TIFFOpen@LIBTIFF_4.0'
```

How could I solve this problem?
The TIFF_LIBRARY and TIFF_INCLUDE have already been set

```
TIFF_LIBRARY                    = /usr/local/lib
TIFF_INCLUDE                    = /usr/include/x86_64-linux-gnu
```

**Comment by rashadkm** [comment]
this is wrong
TIFF_LIBRARY                    = /usr/local/lib

you need something like
TIFF_LIBRARY                    = /usr/local/lib/libtiff.so (check correct file name)
TIFF_LIBRARY is a FILEPATH type not PATH. So it must point to the .so file

**Comment by auroua** [comment]
I have modified the TIFF_LIBRARY, it looks:
```
TIFF_LIBRARY                    = /usr/local/lib/libtiff.so
TIFF_INCLUDE                    = /usr/include/x86_64-linux-gnu
```
but still encounter the same problem.
```
auroua@auroua-ThinkPad-T430:/usr/local/lib$ find libtiff*
libtiff.a
libtiff.la
libtiff.so
libtiff.so.5
libtiff.so.5.2.0
libtiff.so.5.2.4
libtiffxx.a
libtiffxx.la
libtiffxx.so
libtiffxx.so.5
libtiffxx.so.5.2.0
libtiffxx.so.5.2.4
```

**Comment by auroua** [comment]
In FindTIFF.cmake file 
```
SET(TIFF_NAMES ${TIFF_NAMES} tiff libtiff_i libtiff tiff3 libtiff3)

# Added x86_64-linux-gnu path for Ubuntu install
FIND_LIBRARY(TIFF_LIBRARY 
             NAMES ${TIFF_NAMES} 
             PATHS 
             $ENV{TIFF_DIR}/lib
             $ENV{TIFF_DIR}/lib64
             ${CMAKE_INSTALL_PREFIX}/lib
             /usr/local/lib
             /usr/lib 
             /usr/lib/x86_64-linux-gnu)
```
what's the meaning of this line
```
SET(TIFF_NAMES ${TIFF_NAMES} tiff libtiff_i libtiff tiff3 libtiff3)
```
I'm a new learner to cmake

**Comment by auroua** [comment]
It seems libgeotiff depends on libtiff.so.4
I solved this problem in this way:
1 install libtiff.so.4 
2 rebuild libgeotiff based on libtiff.so.4
3 build ossim
the error gone away
This issue can be closed.

**Comment by gpotts** [comment]
Looks like based on the last comment this issue should be closed?  I will close the issue now.

**Comment by Tdai05** [comment]
would you please let me know how  to  install libtiff.so.4? thanks very much for your help

**Comment by omarossim** [comment]
Hello:


We have no idea which environment you are trying to install libtiff.   For CentOS and RHEL it is a tiff-devel RPM.


Take care

Garrett
