### ISSUE TITLE
Submission of changes 

### ISSUE THREAD

**Issue by tushar10sh** [ossimlabs/ossim#60]
I have made some changes to the library, basically fixed some issues with JPEG handling, fixed deprecated code. How do I submit my changes for review? 
Thanks in advance :)

**Comment by gpotts** [comment]
Hello,  Just do a fork and pull request on the dev branch.  Make sure that you have the latest dev then integrate your changes and create a pull request

**Comment by gpotts** [comment]
I will close this issue
